<?php declare(strict_types=1);

// NOTE: This file is autogenerated, please do not edit manually.

namespace Omissis\AlexaSdk\Model;

final class FooBar implements JsonSerializable
{
    /**
     * @var string
     */
    private $foo;

    public function __construct(
        ?string $foo
    ) {
        $this->foo = $foo;
    }

    public function jsonSerialize()
    {
        return [
            'foo' => $this->foo,
        ];
    }

    public static function jsonDeserialize(string $json): self
    {
        $decoded = json_decode($json, true);

        return new self(
            $decoded['foo'] ?? null,
        );
    }

    public function foo(): string
    {
        return $this->foo;
    }
}
