<?php declare(strict_types=1);

// NOTE: This file is autogenerated, please do not edit manually.

namespace Omissis\AlexaSdk\Model;

final class FooBar implements JsonSerializable
{
    /**
     * @var string
     */
    private $foo;

    /**
     * @var float
     */
    private $bar;

    /**
     * @var bool
     */
    private $baz;

    /**
     * @var array
     */
    private $quux;

    /**
     * @var \Omissis\AlexaSdk\Model\BazQuux
     */
    private $corge;

    /**
     * @var null|object
     */
    private $slots;

    /**
     * @var \Omissis\AlexaSdk\Model\Foo\Bar\Baz
     */
    private $fooBarBaz;

    public function __construct(
        string $foo,
        float $bar,
        bool $baz,
        array $quux,
        \Omissis\AlexaSdk\Model\BazQuux $corge,
        ?object $slots,
        \Omissis\AlexaSdk\Model\Foo\Bar\Baz $fooBarBaz
    ) {
        $this->foo = $foo;
        $this->bar = $bar;
        $this->baz = $baz;
        $this->quux = $quux;
        $this->corge = $corge;
        $this->slots = $slots;
        $this->fooBarBaz = $fooBarBaz;
    }

    public function jsonSerialize()
    {
        return [
            'foo' => $this->foo,
            'bar' => $this->bar,
            'baz' => $this->baz,
            'quux' => $this->quux,
            'corge' => $this->corge,
            'slots' => $this->slots,
            'fooBarBaz' => $this->fooBarBaz,
        ];
    }

    public static function jsonDeserialize(string $json): self
    {
        $decoded = json_decode($json, true);

        return new self(
            $decoded['foo'] ?? null,
            $decoded['bar'] ?? null,
            $decoded['baz'] ?? null,
            $decoded['quux'] ?? null,
            $decoded['corge'] ?? null,
            $decoded['slots'] ?? null,
            $decoded['fooBarBaz'] ?? null
        );
    }

    public function foo(): string
    {
        return $this->foo;
    }

    public function bar(): float
    {
        return $this->bar;
    }

    public function baz(): bool
    {
        return $this->baz;
    }

    public function quux(): array
    {
        return $this->quux;
    }

    public function corge(): \Omissis\AlexaSdk\Model\BazQuux
    {
        return $this->corge;
    }

    public function slots(): ?object
    {
        return $this->slots;
    }

    public function fooBarBaz(): \Omissis\AlexaSdk\Model\Foo\Bar\Baz
    {
        return $this->fooBarBaz;
    }
}
