<?php declare(strict_types=1);

// NOTE: This file is autogenerated, please do not edit manually.

namespace Omissis\AlexaSdk\Model\Foo\Bar;

final class Baz2 implements JsonSerializable
{
    /**
     * @var string
     */
    private $title;

    /**
     * @var null|string
     */
    private $body;

    public function __construct(
        string $title,
        ?string $body
    ) {
        $this->title = $title;
        $this->body = $body;
    }

    public function jsonSerialize()
    {
        return [
            'title' => $this->title,
            'body' => $this->body,
        ];
    }

    public static function jsonDeserialize(string $json): self
    {
        $decoded = json_decode($json, true);

        return new self(
            $decoded['title'] ?? null,
            $decoded['body'] ?? null
        );
    }

    public function title(): string
    {
        return $this->title;
    }

    public function body(): ?string
    {
        return $this->body;
    }
}
