<?php declare(strict_types=1);

// NOTE: This file is autogenerated, please do not edit manually.

namespace Omissis\AlexaSdk\Model;

final class Quux implements JsonSerializable
{
    private const ALLOWED_TYPES = [
        \Omissis\AlexaSdk\Model\Foo\Bar\Baz1::class,
        \Omissis\AlexaSdk\Model\Foo\Bar\Baz2::class,
    ];

    /**
     * @var \Omissis\AlexaSdk\Model\Foo\Bar\Baz1|\Omissis\AlexaSdk\Model\Foo\Bar\Baz2
     */
    private $value;

    /**
     * @param \Omissis\AlexaSdk\Model\Foo\Bar\Baz1|\Omissis\AlexaSdk\Model\Foo\Bar\Baz2
     */
    public function __construct($value)
    {
        if (!in_array(get_class($value), self::ALLOWED_TYPES, true)) {
            throw new \InvalidArgumentException(
                sprintf('Value "%s" is of invalid type. Accepted types are: %s', $value, implode(',', self::ALLOWED_TYPES))
            );
        }

        $this->value = $value;
    }

    /**
     * @return \Omissis\AlexaSdk\Model\Foo\Bar\Baz1|\Omissis\AlexaSdk\Model\Foo\Bar\Baz2
     */
    public function getValue()
    {
        return $this->value;
    }

    public function jsonSerialize()
    {
        return $this->value;
    }

    public static function jsonDeserialize(string $json): self
    {
        $decoded = json_decode($json);

        return new self($decoded);
    }
}
